### ISSUE TITLE
Code review 19.05

### ISSUE THREAD

**Issue by predatorfromekb** [altered-dev/prog-gmae#1]
[Вот это](https://github.com/altered-dev/prog-gmae/tree/master/bin/Debug/net6.0) в репозиторий пушить не надо
создай в корне файл `.gitignore` и добавть следующее содержимое
```
bin/
obj/
.idea/
/packages/
riderModule.iml
/_ReSharper.Caches/
```
Предварительно удали все ненужное и бинарное

ты с [vscode-а](https://github.com/altered-dev/prog-gmae/tree/master/.vscode) кодишь?)))

[Тут](https://github.com/altered-dev/prog-gmae/blob/master/Program.cs#L21) дублирования много

Ну и давай сразу депомпозируем на 2 проекта - проект с моделью и проект с представлением

**Comment by altered-dev** [comment]
Все сделано!
